// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SAJ.Data.EntityModels
{
    public partial class Application
    {
        public int Id { get; set; }
        public string Document { get; set; }
        public bool Accepted { get; set; }
    }
}