// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SAJ.Data.EntityModels
{
    public partial class Question
    {
        public string QuestionIdentifier { get; set; }
        public string QuestionText { get; set; }
        public string AcceptedAnswer { get; set; }
    }
}